name1 = input("请输入收卡人:")
name2 = input("请输入送卡人:")
print("#####################")
print(name1)
print()
print("Happy New Year To You.")
print()
print("                      Yours  ",name2)
print("#####################")
